### ISSUE TITLE
`uses` fails: unexpected end-of-file

### ISSUE THREAD

**Issue by chessai** [cachix/cachix-action#105]
I have the following .github/workflows/ci.yml:
```yaml
name: "CI"
on:
  push:
    branches:
      - main
  pull_request: {} # validate all PRs

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes ca-derivations
      - uses: cachix/cachix-action@v10
        with:
          name: sundaeswap
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: echo "hello"
```
When this runs in CI, it fails with:
```
Run cachix/cachix-action@v10
Cachix: installing
  /usr/bin/bash -c nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
  error: unexpected end-of-file
  Error: Action failed with error: Error: The process '/usr/bin/bash' failed with exit code 1
```

EDIT: setting `installCommand: nix profile install nixpkgs#cachix` seems to work.
