### ISSUE TITLE
`cachix: CppStdException "Exception: path '/nix/store/...' is not valid; type: nix::InvalidPath"`

### ISSUE THREAD

**Issue by samuela** [cachix/cachix-action#106]
I'm seeing a weird error trying to use cachix-action. 
```
/home/runner/work/_actions/cachix/cachix-action/v10/dist/main/push-paths.sh /home/runner/.nix-profile/bin/cachix ploop 
cachix: CppStdException "Exception: path '/nix/store/ab3yh7s8rms16b66jlbbzvjaif94ls93-python3.9-apache-beam-2.35.0' is not valid; type: nix::InvalidPath"
Error: Action failed with error: Error: The process '/home/runner/work/_actions/cachix/cachix-action/v10/dist/main/push-paths.sh' failed with exit code 1
```

Here's a link to the failed run: https://github.com/samuela/nixpkgs-upkeep/runs/4976168659?check_suite_focus=true.

Am I doing something wrong?

**Comment by samuela** [comment]
Just got the same thing on a different job:
```
cachix: CppStdException "Exception: path '/nix/store/qli5gyjqm0lizmxz2lqmybwgd3pvz1ji-tensorflow-gpu-2.7.0.drv.chroot' is not valid; type: nix::InvalidPath"
Error: Action failed with error: Error: The process '/home/runner/work/_actions/cachix/cachix-action/v10/dist/main/push-paths.sh' failed with exit code 1
```
Here's the [run](https://github.com/samuela/nixpkgs-upkeep/runs/5012733644?check_suite_focus=true).

**Comment by samuela** [comment]
EDIT: in both of these cases I'm realizing that there were build errors in the job... My expectation was that nix would leave partial file junk in /nix/store though?

**Comment by steveeJ** [comment]
i was wondering how to install cachix 0.7.0 using `cachix/cachix-action@v10` today, and came up with the following solution:

```yml
- name: Setup cachix
  uses: cachix/cachix-action@v10
  with:
    (...)
    installCommand: |
      nix-env -if https://github.com/cachix/cachix/tarball/cachix-api-0.7.0 \
        --substituters 'https://cache.nixos.org https://cachix.cachix.org' \
        --trusted-public-keys 'cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY='
```
