### ISSUE TITLE
Add flag to allow failures

### ISSUE THREAD

**Issue by elsirion** [cachix/cachix-action#131]
A recent cachix outage broke our [builds at fedimint](https://github.com/fedimint/fedimint/actions/runs/3659426050/jobs/6185787623#step:10:10). This should not be the case since we could just build from source or not push in this scenario.

There does not seem to be an easy way to make GH Actions ignore the failure of an action. If I was running things manually I'd just add a ` || true` after the cachix command. Ideally this action would have an `ignore_failure` (default to false to maintain default behavior) flag that does exactly that.

**Comment by sandydoo** [comment]
For anyone looking this up in the future, you can use `continue-on-error` to let the job continue should the action fail:

```yml
- uses: cachix/cachix-action@v12
  continue-on-error: true
  with:
    name: my-cache
    authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
```
