### ISSUE TITLE
cachix/cachix-action fails to run

### ISSUE THREAD

**Issue by akirak** [cachix/cachix-action#137]
The action used to work before, but it now unconditionally fails with the following error in [my workflow](https://github.com/akirak/homelab/actions/runs/4273794443/jobs/7439938667):

> Cachix: using cache akirak
  /nix/var/nix/profiles/per-user/runner/profile/bin/cachix use akirak
  Binary cache akirak doesn't exist or it's private and you don't have access it::error::Action failed with error: Error: The process '/nix/var/nix/profiles/per-user/runner/profile/bin/cachix' failed with exit code 1

with the following config:

```yaml
    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
```

The binary cache does exist, and `cachix use akirak` successfully runs locally:

> ❯ cachix use akirak
Configured https://akirak.cachix.org binary cache in /home/akirakomamura/.config/nix/nix.conf

Do you have any idea what's wrong here?
