### ISSUE TITLE
Cachix takes a long time to install in GitHub Actions CI

### ISSUE THREAD

**Issue by djacu** [cachix/cachix-action#172]
I recently setup a new cache and followed the tutorial to integrate it into my repositories CI with GitHub Actions. The cache does work but the install step takes ~40 seconds. I was told it should be close to ~2 seconds.

<details>
  <summary>workflow</summary>

```yaml
# .github/workflows/netlify.yml
name: Build and Deploy to Netlify

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cachix
        uses: cachix/cachix-action@v14
        with:
          name: djacu-nixos-modules-lessons
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Site
        run: |
          nix build .#site
          mkdir ./dist
          cp -R ./result/* ./dist/
          chmod -R +w ./dist/

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          enable-commit-status: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
```

</details>

[cachix-action-logs.txt](https://github.com/cachix/cachix-action/files/14231312/cachix-action-logs.txt)
