### ISSUE TITLE
Using another cachix cache within the action

### ISSUE THREAD

**Issue by NorfairKing** [cachix/cachix-action#18]
My project `validity` is heavily used in my project `smos`.
They have separate cachix caches because validity is a widely used library by itself.
In the ci for smos, I'd like to use the cachix cache for validity.

**Comment by domenkozar** [comment]
This will be possible with #19 like:

```yaml
- uses: cachix/cachix-action@v3
      with:
        name: validity
        skipNixBuild: true
- uses: cachix/cachix-action@v3
      with:
        name: mycache
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
```

**Comment by NorfairKing** [comment]
I misread your comment. It's indeed not possible yet: https://github.com/NorfairKing/smos/commit/b68cbe7f625eed09c6ac5b7dd651d18195290db5/checks?check_suite_id=366919977
But will try it out as soon as #19 is merged, thank you!

**Comment by domenkozar** [comment]
Hopefully very soon, if I find out why macOS CI is failing.

**Comment by domenkozar** [comment]
Could you try now with:

```
- uses: cachix/cachix-action@releases/v3
      with:
        name: validity
        skipNixBuild: true
- uses: cachix/cachix-action@releases/v3
      with:
        name: smos
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
```
