### ISSUE TITLE
Add the ability to pass `--arg` / `--argstr` to nix-build

### ISSUE THREAD

**Issue by anmonteiro** [cachix/cachix-action#24]
I have a usecase for building a library against multiple versions of the OCaml compiler.

Right now this action supports `file` and `attributes` but not `--arg` or `--argstr` which would be helpful to avoid repeating myself in the GH action. Ideally I'd be able to do something like:

```yaml
    - uses: cachix/cachix-action@v3
      with:
        name: my-cache-name
        argstr: 
          - ocamlVersion ${{ matrix.ocamlVersion }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

strategy:
  matrix:
    ocamlVersion: [4_06, 4_07, 4_08, 4_09]
```
