### ISSUE TITLE
Choosing when to run cachix-action

### ISSUE THREAD

**Issue by bolt12** [cachix/cachix-action#53]
I have a Haskell project that uses GH Actions to run CI with 2 different GHC versions. However I only want to push to cachix the most recent GHC version supported.

I used this:

```yaml
    - uses: cachix/cachix-action@v6
      if: matrix.ghc == 'ghc883' # Push to cachix only the most up to date GHC version
      with:
        name: bolt12-laop
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
```

But it still runs the post cachix-action thingy on the other version.

Is there a way around this?
